[global]
type=global
user_agent=Asterisk-PBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5070

# ==================== Extension 6001 ====================
[6001]
type=endpoint
context=prepaid-outbound
disallow=all
allow=ulaw
allow=alaw
auth=6001_auth
aors=6001
callerid=User 1 <201001234567>
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[6001_auth]
type=auth
auth_type=userpass
username=6001
password=password6001
realm=127.0.0.1

[6001]
type=aor
max_contacts=50

# ==================== Extension 6002 ====================
[6002]
type=endpoint
context=prepaid-outbound
disallow=all
allow=ulaw
allow=alaw
auth=6002_auth
aors=6002
callerid=User 2 <201009876543>
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[6002_auth]
type=auth
auth_type=userpass
username=6002
password=password6002
realm=127.0.0.1

[6002]
type=aor
max_contacts=50
